# Price Determining Function

Creating a simple function that determines price according to merit order data.

In [8]:
# Let's load in the necessary packages
import pandas as pd
import datetime
import os
import timeit
import matplotlib.pyplot as plt
from ortools.linear_solver import pywraplp
# from ortools.sat.python import cp_model
import numpy as np

#### Function from Prof. Leach
Will use here the code that Professor Leach gave.
It's a function that gets the new price for a certain hour.

In [15]:
# Loading in the data first.
# Let's load in the data here, and for now, let's make it just for four hours.

file_name = os.fsdecode("marco_data.csv")
workbook = pd.read_csv(file_name)
workbook = workbook.filter(items=["date", "he", "size","flexible","price"]) # Gets the columns that we need

workbook = workbook.query('date=="2024-04-10"'and 'he==15') # Remove this to take out the filter for the day.

# Getting the columns we need.
merit_data = workbook.filter(items=["date", "he", "size","flexible","price"]) # Gets the columns that we need

#pd.set_option('display.max_rows',50)

# Temporary peek:
temp = merit_data.copy()
#temp

            date  he      size flexible   price
3518  2024-04-10  15    0.0395        N    0.00
3519  2024-04-10  15    0.0648        N    0.00
3520  2024-04-10  15    0.0752        N    0.00
3521  2024-04-10  15    0.1373        N    0.00
3522  2024-04-10  15    0.1919        N    0.00
...          ...  ..       ...      ...     ...
3785  2024-04-10  15   16.0000        Y  999.99
3786  2024-04-10  15   25.0000        Y  999.99
3787  2024-04-10  15   42.0000        N  999.99
3788  2024-04-10  15   80.0000        Y  999.99
3789  2024-04-10  15  174.0000        Y  999.99

[272 rows x 5 columns]

In [28]:
# Making everything we have above into a function:
#THIS IS YOU MAKING A 3rd filtered dataset.

bids = merit_data.query('he==15')
#set ail for testing
ail = 2000

# def pricing(bids, ail): # Bids is self-explanatory, so set of bids needed.
bids=bids.sort_values('price').reset_index(drop = True)
# bids=bids.assign(merit=bids['size'].cumsum())
bids['merit'] = bids['size'].cumsum() # Old code is above

bids = bids.assign(surplus=bids['merit']-ail)

#bids['surplus'] = bids['merit'] - ail
bids

           date  he      size flexible   price       merit     surplus
0    2024-04-10  15    0.0395        N    0.00      0.0395  -1999.9605
1    2024-04-10  15   43.0000        Y    0.00     43.0395  -1956.9605
2    2024-04-10  15   44.0000        N    0.00     87.0395  -1912.9605
3    2024-04-10  15   45.0000        N    0.00    132.0395  -1867.9605
4    2024-04-10  15   46.0000        N    0.00    178.0395  -1821.9605
..          ...  ..       ...      ...     ...         ...         ...
267  2024-04-10  15    2.0000        Y  999.99  12101.7169  10101.7169
268  2024-04-10  15    2.0000        Y  999.99  12103.7169  10103.7169
269  2024-04-10  15    2.0000        Y  999.99  12105.7169  10105.7169
270  2024-04-10  15    5.0000        Y  999.99  12110.7169  10110.7169
271  2024-04-10  15  174.0000        Y  999.99  12284.7169  10284.7169

[272 rows x 7 columns]

In [30]:
#pick the max negative surplus
last_full=bids.query('surplus<=0')['surplus'].idxmax()
print(last_full,bids['surplus'][last_full])
# Made this change to get the actual energy needed left
e_needed=-bids['surplus'][last_full] # Getting the last negative surplus value since that's the amound lacking
print(e_needed)
print(bids.loc[last_full-2:last_full+2])

41 -80.94679999999971
80.94679999999971
          date  he      size flexible  price      merit   surplus
39  2024-04-10  15   79.0882        N    0.0  1760.2235 -239.7765
40  2024-04-10  15   79.1963        N    0.0  1839.4198 -160.5802
41  2024-04-10  15   79.6334        N    0.0  1919.0532  -80.9468
42  2024-04-10  15  139.2640        N    0.0  2058.3172   58.3172
43  2024-04-10  15  140.0000        N    0.0  2198.3172  198.3172

In [31]:
#dont' divide this stuff like this. e_needed and last_full will only be right when you run it the first time.
while(e_needed>0):
    last_full+=1 #do this here
    if(bids['size'][last_full]<e_needed): #dispatch it
        e_needed-=bids['size'][last_full]
    elif (bids['size'][last_full]>=e_needed) and (bids['flexible'][last_full]=="Y"): #dispatch part of it 
        e_needed-=e_needed
    # Made changes in the bids below to get the price accurately
    price=bids['price'][last_full-1]
    print(e_needed,last_full-1,price)
print(bids.loc[last_full-2:last_full+2])

80.94679999999971 41 0.0
80.94679999999971 42 0.0
80.94679999999971 43 0.0
0.0 44 0.0
          date  he     size flexible  price      merit   surplus
43  2024-04-10  15  140.000        N    0.0  2198.3172  198.3172
44  2024-04-10  15  145.000        N    0.0  2343.3172  343.3172
45  2024-04-10  15  153.000        Y    0.0  2496.3172  496.3172
46  2024-04-10  15  158.000        N    0.0  2654.3172  654.3172
47  2024-04-10  15  162.996        N    0.0  2817.3132  817.3132

In [44]:
bids

,date,he,size,flexible,price,ail,merit,surplus
0,2018-08-05,15,0.0081,N,0.00,8980.7614,0.0081,-1999.9919
1,2018-08-05,15,80.0000,Y,0.00,8980.7614,80.0081,-1919.9919
2,2018-08-05,15,75.0000,N,0.00,8980.7614,155.0081,-1844.9919
3,2018-08-05,15,71.0000,Y,0.00,8980.7614,226.0081,-1773.9919
4,2018-08-05,15,64.0000,N,0.00,8980.7614,290.0081,-1709.9919
5,2018-08-05,15,60.0000,N,0.00,8980.7614,350.0081,-1649.9919
6,2018-08-05,15,50.0000,Y,0.00,8980.7614,400.0081,-1599.9919
7,2018-08-05,15,45.0000,N,0.00,8980.7614,445.0081,-1554.9919
8,2018-08-05,15,43.0000,Y,0.00,8980.7614,488.0081,-1511.9919
9,2018-08-05,15,41.0000,Y,0.00,8980.7614,529.0081,-1470.9919
10,2018-08-05,15,110.0000,N,0.00,8980.7614,639.0081,-1360.9919
11,2018-08-05,15,41.0000,N,0.00,8980.7614,680.0081,-1319.9919
12,2018-08-05,15,40.0000,N,0.00,8980.7614,720.0081,-1279.9919
13,2018-08-05,15,40.0000,N,0.00,8980.7614,760.0081,-1239.9919
14,2018-08-05,15,36.0000,Y,0.00,8980.7614,796.0081,-1203.9919
15,2018-08-05,15,35.0000,N,0.00,8980.7614,831.0081,-1168.9919
16,2018-08-05,15,35.0000,N,0.00,8980.7614,866.0081,-1133.9919
17,2018-08-05,15,33.0000,N,0.00,8980.7614,899.0081,-1100.9919
18,2018-08-05,15,32.0000,N,0.00,8980.7614,931.0081,-1068.9919
19,2018-08-05,15,31.0000,N,0.00,8980.7614,962.0081,-1037.9919
20,2018-08-05,15,26.0000,N,0.00,8980.7614,988.0081,-1011.9919
21,2018-08-05,15,40.0000,N,0.00,8980.7614,1028.0081,-971.9919
22,2018-08-05,15,115.0000,N,0.00,8980.7614,1143.0081,-856.9919
23,2018-08-05,15,117.0000,Y,0.00,8980.7614,1260.0081,-739.9919
24,2018-08-05,15,120.0000,N,0.00,8980.7614,1380.0081,-619.9919
25,2018-08-05,15,200.0000,N,0.00,8980.7614,1580.0081,-419.9919
26,2018-08-05,15,200.0000,N,0.00,8980.7614,1780.0081,-219.9919
27,2018-08-05,15,199.0000,N,0.00,8980.7614,1979.0081,-20.9919
28,2018-08-05,15,182.0000,N,0.00,8980.7614,2161.0081,161.0081
29,2018-08-05,15,176.0000,N,0.00,8980.7614,2337.0081,337.0081
30,2018-08-05,15,170.0000,N,0.00,8980.7614,2507.0081,507.0081
31,2018-08-05,15,163.0000,N,0.00,8980.7614,2670.0081,670.0081
32,2018-08-05,15,161.0000,Y,0.00,8980.7614,2831.0081,831.0081
33,2018-08-05,15,160.0000,N,0.00,8980.7614,2991.0081,991.0081
34,2018-08-05,15,155.0000,Y,0.00,8980.7614,3146.0081,1146.0081
35,2018-08-05,15,150.0000,N,0.00,8980.7614,3296.0081,1296.0081
36,2018-08-05,15,150.0000,Y,0.00,8980.7614,3446.0081,1446.0081
37,2018-08-05,15,150.0000,Y,0.00,8980.7614,3596.0081,1596.0081
38,2018-08-05,15,150.0000,N,0.00,8980.7614,3746.0081,1746.0081
39,2018-08-05,15,149.0000,N,0.00,8980.7614,3895.0081,1895.0081
40,2018-08-05,15,147.0000,N,0.00,8980.7614,4042.0081,2042.0081
41,2018-08-05,15,142.0000,Y,0.00,8980.7614,4184.0081,2184.0081
42,2018-08-05,15,138.0000,N,0.00,8980.7614,4322.0081,2322.0081
43,2018-08-05,15,136.0000,N,0.00,8980.7614,4458.0081,2458.0081
44,2018-08-05,15,133.0000,Y,0.00,8980.7614,4591.0081,2591.0081
45,2018-08-05,15,130.0000,Y,0.00,8980.7614,4721.0081,2721.0081
46,2018-08-05,15,25.0000,Y,0.00,8980.7614,4746.0081,2746.0081
47,2018-08-05,15,24.0000,N,0.00,8980.7614,4770.0081,2770.0081
48,2018-08-05,15,23.0000,N,0.00,8980.7614,4793.0081,2793.0081
49,2018-08-05,15,23.0000,N,0.00,8980.7614,4816.0081,2816.0081
50,2018-08-05,15,5.0000,Y,0.00,8980.7614,4821.0081,2821.0081
51,2018-08-05,15,4.0000,Y,0.00,8980.7614,4825.0081,2825.0081
52,2018-08-05,15,4.0000,Y,0.00,8980.7614,4829.0081,2829.0081
53,2018-08-05,15,4.0000,Y,0.00,8980.7614,4833.0081,2833.0081
54,2018-08-05,15,4.0000,Y,0.00,8980.7614,4837.0081,2837.0081
55,2018-08-05,15,4.0000,Y,0.00,8980.7614,4841.0081,2841.0081
56,2018-08-05,15,4.0000,N,0.00,8980.7614,4845.0081,2845.0081
57,2018-08-05,15,4.0000,Y,0.00,8980.7614,4849.0081,2849.0081
58,2018-08-05,15,3.0000,Y,0.00,8980.7614,4852.0081,2852.0081
59,2018-08-05,15,2.0000,Y,0.00,8980.7614,4854.0081,2854.0081
60,2018-08-05,15,1.9210,N,0.00,8980.7614,4855.9291,2855.9291
61,2018-08-05,15,1.4190,N,0.00,8980.7614,4857.3481,2857.3481
62,2018-08-05,15,1.3427,N,0.00,8980.7614,4858.6908,2858.6908
63,2018-08-05,15,1.3256,N,0.00,8980.7614,4860.0164,2860.0164
64,2018-08-05,15,0.8020,N,0.00,8980.7614,4860.8184,2860.8184
65,2018-08-05,15,0.6995,N,0.00,8980.7614,4861.5179,2861.5179
66,2018-08-05,15,0.5429,N,0.00,8980.7614,4862.0608,2862.0608
67,2018-08-05,15,0.1725,N,0.00,8980.7614,4862.2333,2862.2333
68,2018-08-05,15,0.1269,N,0.00,8980.7614,4862.3602,2862.3602
69,2018-08-05,15,0.1112,N,0.00,8980.7614,4862.4714,2862.4714
70,2018-08-05,15,0.0770,N,0.00,8980.7614,4862.5484,2862.5484
71,2018-08-05,15,5.0000,Y,0.00,8980.7614,4867.5484,2867.5484
72,2018-08-05,15,380.0000,Y,0.00,8980.7614,5247.5484,3247.5484
73,2018-08-05,15,5.0000,Y,0.00,8980.7614,5252.5484,3252.5484
74,2018-08-05,15,5.0000,N,0.00,8980.7614,5257.5484,3257.5484
75,2018-08-05,15,20.0000,N,0.00,8980.7614,5277.5484,3277.5484
76,2018-08-05,15,19.0000,N,0.00,8980.7614,5296.5484,3296.5484
77,2018-08-05,15,18.0000,N,0.00,8980.7614,5314.5484,3314.5484
78,2018-08-05,15,17.0000,Y,0.00,8980.7614,5331.5484,3331.5484
79,2018-08-05,15,14.3360,N,0.00,8980.7614,5345.8844,3345.8844
80,2018-08-05,15,14.0000,Y,0.00,8980.7614,5359.8844,3359.8844
81,2018-08-05,15,13.0000,N,0.00,8980.7614,5372.8844,3372.8844
82,2018-08-05,15,13.0000,N,0.00,8980.7614,5385.8844,3385.8844
83,2018-08-05,15,12.0000,Y,0.00,8980.7614,5397.8844,3397.8844
84,2018-08-05,15,11.0000,Y,0.00,8980.7614,5408.8844,3408.8844
85,2018-08-05,15,10.0000,Y,0.00,8980.7614,5418.8844,3418.8844
86,2018-08-05,15,10.0000,Y,0.00,8980.7614,5428.8844,3428.8844
87,2018-08-05,15,10.0000,Y,0.00,8980.7614,5438.8844,3438.8844
88,2018-08-05,15,10.0000,Y,0.00,8980.7614,5448.8844,3448.8844
89,2018-08-05,15,9.0000,Y,0.00,8980.7614,5457.8844,3457.8844
90,2018-08-05,15,8.0000,Y,0.00,8980.7614,5465.8844,3465.8844
91,2018-08-05,15,7.3770,N,0.00,8980.7614,5473.2614,3473.2614
92,2018-08-05,15,7.0000,Y,0.00,8980.7614,5480.2614,3480.2614
93,2018-08-05,15,5.0000,N,0.00,8980.7614,5485.2614,3485.2614
94,2018-08-05,15,5.0000,N,0.00,8980.7614,5490.2614,3490.2614
95,2018-08-05,15,5.0000,N,0.00,8980.7614,5495.2614,3495.2614
96,2018-08-05,15,5.0000,Y,0.00,8980.7614,5500.2614,3500.2614
97,2018-08-05,15,390.0000,N,0.00,8980.7614,5890.2614,3890.2614
98,2018-08-05,15,32.0000,Y,6.25,8980.7614,5922.2614,3922.2614
99,2018-08-05,15,26.0000,N,6.95,8980.7614,5948.2614,3948.2614
100,2018-08-05,15,37.0000,N,7.15,8980.7614,5985.2614,3985.2614
101,2018-08-05,15,32.0000,Y,7.54,8980.7614,6017.2614,4017.2614
102,2018-08-05,15,1.0000,N,8.00,8980.7614,6018.2614,4018.2614
103,2018-08-05,15,29.0000,N,8.12,8980.7614,6047.2614,4047.2614
104,2018-08-05,15,11.0000,Y,8.69,8980.7614,6058.2614,4058.2614
105,2018-08-05,15,4.0000,Y,9.00,8980.7614,6062.2614,4062.2614
106,2018-08-05,15,36.0000,Y,9.78,8980.7614,6098.2614,4098.2614
107,2018-08-05,15,29.0000,Y,10.00,8980.7614,6127.2614,4127.2614
108,2018-08-05,15,22.0000,Y,11.16,8980.7614,6149.2614,4149.2614
109,2018-08-05,15,1.0000,N,11.30,8980.7614,6150.2614,4150.2614
110,2018-08-05,15,138.0000,Y,12.94,8980.7614,6288.2614,4288.2614
111,2018-08-05,15,145.0000,Y,13.33,8980.7614,6433.2614,4433.2614
112,2018-08-05,15,50.0000,Y,14.16,8980.7614,6483.2614,4483.2614
113,2018-08-05,15,26.0000,Y,14.30,8980.7614,6509.2614,4509.2614
114,2018-08-05,15,74.0000,Y,15.03,8980.7614,6583.2614,4583.2614
115,2018-08-05,15,50.0000,Y,15.98,8980.7614,6633.2614,4633.2614
116,2018-08-05,15,50.0000,Y,17.55,8980.7614,6683.2614,4683.2614
117,2018-08-05,15,45.0000,Y,18.25,8980.7614,6728.2614,4728.2614
118,2018-08-05,15,33.0000,N,18.88,8980.7614,6761.2614,4761.2614
119,2018-08-05,15,75.0000,Y,18.88,8980.7614,6836.2614,4836.2614
120,2018-08-05,15,40.0000,Y,19.36,8980.7614,6876.2614,4876.2614
121,2018-08-05,15,63.0000,Y,19.45,8980.7614,6939.2614,4939.2614
122,2018-08-05,15,38.0000,N,19.95,8980.7614,6977.2614,4977.2614
123,2018-08-05,15,40.0000,Y,19.99,8980.7614,7017.2614,5017.2614
124,2018-08-05,15,56.0000,N,21.50,8980.7614,7073.2614,5073.2614
125,2018-08-05,15,33.0000,N,22.00,8980.7614,7106.2614,5106.2614
126,2018-08-05,15,20.0000,Y,24.73,8980.7614,7126.2614,5126.2614
127,2018-08-05,15,57.0000,Y,24.85,8980.7614,7183.2614,5183.2614
128,2018-08-05,15,59.0000,Y,25.05,8980.7614,7242.2614,5242.2614
129,2018-08-05,15,70.0000,Y,25.10,8980.7614,7312.2614,5312.2614
130,2018-08-05,15,75.0000,Y,25.15,8980.7614,7387.2614,5387.2614
131,2018-08-05,15,32.0000,Y,25.51,8980.7614,7419.2614,5419.2614
132,2018-08-05,15,93.0000,Y,25.55,8980.7614,7512.2614,5512.2614
133,2018-08-05,15,38.0000,Y,25.82,8980.7614,7550.2614,5550.2614
134,2018-08-05,15,43.0000,N,26.05,8980.7614,7593.2614,5593.2614
135,2018-08-05,15,12.0000,Y,26.65,8980.7614,7605.2614,5605.2614
136,2018-08-05,15,33.0000,N,26.68,8980.7614,7638.2614,5638.2614
137,2018-08-05,15,5.0000,Y,27.14,8980.7614,7643.2614,5643.2614
138,2018-08-05,15,181.0000,Y,27.18,8980.7614,7824.2614,5824.2614
139,2018-08-05,15,181.0000,Y,27.19,8980.7614,8005.2614,6005.2614
140,2018-08-05,15,65.0000,Y,31.00,8980.7614,8070.2614,6070.2614
141,2018-08-05,15,83.0000,Y,31.50,8980.7614,8153.2614,6153.2614
142,2018-08-05,15,15.0000,Y,31.60,8980.7614,8168.2614,6168.2614
143,2018-08-05,15,161.0000,Y,31.75,8980.7614,8329.2614,6329.2614
144,2018-08-05,15,11.0000,Y,33.00,8980.7614,8340.2614,6340.2614
145,2018-08-05,15,7.0000,Y,33.25,8980.7614,8347.2614,6347.2614
146,2018-08-05,15,243.0000,Y,33.25,8980.7614,8590.2614,6590.2614
147,2018-08-05,15,243.0000,Y,33.26,8980.7614,8833.2614,6833.2614
148,2018-08-05,15,8.0000,Y,38.12,8980.7614,8841.2614,6841.2614
149,2018-08-05,15,20.0000,Y,40.00,8980.7614,8861.2614,6861.2614
150,2018-08-05,15,15.0000,N,41.50,8980.7614,8876.2614,6876.2614
151,2018-08-05,15,8.0000,Y,42.00,8980.7614,8884.2614,6884.2614
152,2018-08-05,15,7.0000,Y,45.34,8980.7614,8891.2614,6891.2614
153,2018-08-05,15,235.0000,Y,46.06,8980.7614,9126.2614,7126.2614
154,2018-08-05,15,2.0000,N,47.49,8980.7614,9128.2614,7128.2614
155,2018-08-05,15,8.0000,N,50.00,8980.7614,9136.2614,7136.2614
156,2018-08-05,15,25.0000,N,55.00,8980.7614,9161.2614,7161.2614
157,2018-08-05,15,41.0000,Y,58.88,8980.7614,9202.2614,7202.2614
158,2018-08-05,15,11.0000,Y,60.00,8980.7614,9213.2614,7213.2614
159,2018-08-05,15,15.0000,Y,71.65,8980.7614,9228.2614,7228.2614
160,2018-08-05,15,15.0000,Y,98.64,8980.7614,9243.2614,7243.2614
161,2018-08-05,15,251.0000,Y,109.89,8980.7614,9494.2614,7494.2614
162,2018-08-05,15,4.0000,N,110.00,8980.7614,9498.2614,7498.2614
163,2018-08-05,15,256.0000,Y,117.93,8980.7614,9754.2614,7754.2614
164,2018-08-05,15,5.0000,Y,150.00,8980.7614,9759.2614,7759.2614
165,2018-08-05,15,5.0000,Y,500.00,8980.7614,9764.2614,7764.2614
166,2018-08-05,15,41.0000,N,804.65,8980.7614,9805.2614,7805.2614
167,2018-08-05,15,19.0000,N,822.35,8980.7614,9824.2614,7824.2614
168,2018-08-05,15,91.0000,N,900.00,8980.7614,9915.2614,7915.2614
169,2018-08-05,15,60.0000,Y,961.24,8980.7614,9975.2614,7975.2614
170,2018-08-05,15,60.0000,Y,968.75,8980.7614,10035.2614,8035.2614
171,2018-08-05,15,64.0000,Y,974.25,8980.7614,10099.2614,8099.2614
172,2018-08-05,15,4.0000,Y,986.53,8980.7614,10103.2614,8103.2614
173,2018-08-05,15,4.0000,Y,986.55,8980.7614,10107.2614,8107.2614
174,2018-08-05,15,17.0000,Y,988.12,8980.7614,10124.2614,8124.2614
175,2018-08-05,15,11.0000,Y,989.65,8980.7614,10135.2614,8135.2614
176,2018-08-05,15,1.0000,Y,999.00,8980.7614,10136.2614,8136.2614
177,2018-08-05,15,5.0000,N,999.00,8980.7614,10141.2614,8141.2614
178,2018-08-05,15,5.0000,N,999.00,8980.7614,10146.2614,8146.2614
179,2018-08-05,15,130.0000,Y,999.72,8980.7614,10276.2614,8276.2614
180,2018-08-05,15,50.0000,Y,999.87,8980.7614,10326.2614,8326.2614
181,2018-08-05,15,153.0000,Y,999.95,8980.7614,10479.2614,8479.2614
182,2018-08-05,15,7.0000,Y,999.99,8980.7614,10486.2614,8486.2614
183,2018-08-05,15,6.0000,Y,999.99,8980.7614,10492.2614,8492.2614
184,2018-08-05,15,5.0000,Y,999.99,8980.7614,10497.2614,8497.2614
185,2018-08-05,15,5.0000,Y,999.99,8980.7614,10502.2614,8502.2614
186,2018-08-05,15,5.0000,Y,999.99,8980.7614,10507.2614,8507.2614
187,2018-08-05,15,4.0000,Y,999.99,8980.7614,10511.2614,8511.2614
188,2018-08-05,15,4.0000,Y,999.99,8980.7614,10515.2614,8515.2614
189,2018-08-05,15,3.0000,Y,999.99,8980.7614,10518.2614,8518.2614
190,2018-08-05,15,3.0000,Y,999.99,8980.7614,10521.2614,8521.2614
191,2018-08-05,15,3.0000,Y,999.99,8980.7614,10524.2614,8524.2614
192,2018-08-05,15,10.0000,Y,999.99,8980.7614,10534.2614,8534.2614
193,2018-08-05,15,3.0000,Y,999.99,8980.7614,10537.2614,8537.2614
194,2018-08-05,15,2.0000,Y,999.99,8980.7614,10539.2614,8539.2614
195,2018-08-05,15,1.0000,Y,999.99,8980.7614,10540.2614,8540.2614
196,2018-08-05,15,4.0000,Y,999.99,8980.7614,10544.2614,8544.2614
197,2018-08-05,15,25.0000,Y,999.99,8980.7614,10569.2614,8569.2614